### ISSUE TITLE
Dart null safety support

### ISSUE THREAD

**Issue by jacksonw765** [gmetekorkmaz/SwipeStack#15]
Would love to add support for Dart null safety.

**Comment by jacksonw765** [comment]
I added support for this myself. Feel free to merge. 

````
swipe_stack:
    git:
      url: https://github.com/jacksonw765/SwipeStack.git
      ref: e081d36
````
